Match the void return types specified by the parent class
Because PHPUnit 8 introduced explicit void return type for setUp and setUpBeforeClass
we need to match this otherwise we get a compiler error.  E.g.

```
Fatal error: Declaration of adrianclay\git\References\ReferencesArrayTest::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void
```